---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdns-admin-ingress
  namespace: pdns
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: pdns.home.thejimnicholson.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdns-admin
            port: 
              number: 80