---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdns-pv
  namespace: pdns
  labels:
    app: pdns
spec:
  storageClassName: "local-path"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
  nfs:
    server: 10.0.96.14
    path: "/mnt/data/pdns-admin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdns-admin-claim
  namespace: pdns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 5Gi
  volumeName: pdns-pv