---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdns-admin-claim
  namespace: pdns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi